### ISSUE TITLE
what is the benefit of not thelonious chains within epm?

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#167]
i am increasingly unconvinced of the benefits of having multiple chain types usable from this tool. 

epm's functionality can roughly be broken down into three major areas:

1. dapp//project management (this includes refs and most of new)
2. blockchain administration functionality (config, etc.) and operation functionality (checkout, run)
3. smart contract package management

`1` is only applicable to thelonious

`2` is partially applicable to all three currently vetted types but the difficult parts of `2` are really only applicable to thelonious

`3` should really only be done via rpc going forward as that will give us the most flexibility as to where a particular container is running (locally, remote, who cares). indeed as we break out the key signing function into a signing microservice/daemon, then we definitely should be using the rpc.

## costs-benefits as i see them

costs:

* this multibinary setup is going to be a bit complex to maintain, 
* setup currently feels significantly more sluggish than yesterday (before i rebased)

benefits:

* universal command line interface ...? 

the benefit is all well and good but if folks want eth or mint they can much more easily install those projects' tools and use them. i am not sure what value having those libs be integrated into epm gives our users. 

maybe i'm wrong, but on balance I think that we need to focus this tool on being the best cli for thelonious because it seems to me its starting to get in our way.

**N.B.**, this somewhat relates to #161

**Comment by dennismckinnon** [comment]
There are two benefits I see that are not on your list. The universal nature of the tool makes it a bridging point for people working solely on one of the other platforms to work on others. It also reduces the cost of trying out things on different systems. For example I am currently able to work with two different vms and debug contracts for thelonimint before its completed.  I feel like the smart contracting capability is being downplayed.

Second. we don't really know where dapps are going. I would expect that multi chain systems are going to be core to the future and its an area we currently dominate. 

For costs I have not noticed as large of an impact for running as you have. It is a little slower for building but that's because I always just do `make` and not the component i need updated. But maybe its something that can be worked on.

As for complexity of maintainence i defer to ethan. On the whole my evaluation of this issue is that the benefits of cross chain capability and the fact that its the only tool capable of this far outweigh the costs. Its possible that epm could become the definitive blockchain tool and I don't think we should gimp it just yet. Redesign may be in order though if its an issue.

**Comment by compleatang** [comment]
cool. a few responses.

it is a bridge in the sense of what skin we are putting onto a cli (which is a very small piece of the overall codebase) to instantiate, start, and stop a chain (and perhaps configure). we can achieve the same end state by using docker (`docker run tendermint/tendermint`), or external binaries (`$GOPATH/bin/mint`) and smartly wrapping these commands. that would lower our technical debt significantly over the current state of affairs in my opinion (why? better socket design between the pieces of the stack, basically). 

docker would also achieve the same purpose of reduced cost of trying things.

i agree with the goal of continuing to support multi chain systems, i just think that it is achievable in a more simple, elegant, and sustainable way. 

> i feel like the smart contracting capability is being downplayed.

didn't mean to imply that, because this is a clear and significant value add. but we can have the exact same user interface with a much improved user experience by pulling the blockchains (preferably all of them, but at least the not-thelonious ones) out of here, running them as separate binaries or dockers and using their rpc's exclusively for smart contract package deployments. unless i'm missing some functionality we need to process `.pdx`'s which is not available from the rpc (in which case it is really an issue with the rpc so better to fix that than to patch it from a tool that is becoming increasingly unwieldy).

pulling the blockchains out has the added benefit that we will then be able to have full support for all relevant OS's from our primary (command line) tool (windows users just will need to run their blockchains in containers).

**Comment by ebuchman** [comment]
> i just think that it is achievable in a more simple, elegant, and sustainable way

would love to know how. 

i think a smart cli for multichain will be essential. not sure exactly what you feel is slowing things down. how is it increasingly unweildly?

**Comment by compleatang** [comment]
> would love to know how.

`docker` + better optimization of rpc (this issue really should be read in parallel with #161 )

> i think a smart cli for multichain will be essential

i don't disagree with this. indeed it is what i'm trying to parse here. `essential` to whom? for what purpose? 

i'm asking because i have been a near-daily user of this tool since November(?) and have literally *never* used non thelonious blockchains because I have never had the need; not once. Andreas whenever he works on Solidity uses aleth because our eth fork is old and epm-eth is therefore currently outdated (more technical debt, not hard to maintain but something we do need to (currently) maintain). Dennis has been using Tendermint to test solidity via epm-mint which is great, but I assume the entirety of the functionality he's using is: (1) turning on a blockchain and (2) testing contracts against the blockchain's vm (which is fully accomplishable via RPC) and (3) shutting down a blockchain.

as I said, all of that functionality we do not lose by moving the blockchains out of epm.

> what you feel is slowing things down

example (this **literally** just happened as I was typing this response) checking `time epm plop chainid` to confirm last night's sluggishness (~1s to plop a chainid) is still happening -> `There is no chain checked out`; shit `epm refs ls` -> `There is no chain checked out`; shit `cd .. && make` -> compilation errors in tendermint (which are irrelevant to me cause I'm not using tendermint); shit `epm-binary-generator ./cmd/epm ./commands thelonious` -> ok. `epm plop chainid` -> no chain; `epm refs ls` -> no chain. `ls ~/.decerver/blockchains/refs` ... `epm checkout test1`; ok `time epm plop chainid`

```
3389a81920bba8834dc20b3fb230069afb34b7ad
epm plop chainid  0.25s user 0.02s system 100% cpu 0.266 total
```

250ms to plop a chainid which isn't bad and definitely not as laggy as it was last night. 

Just to see how long a plop chainid was taking on Eris Industries' main cli tool I had to go through all that pain; admittedly the compilation step was overkill but its necessary when switching between branches in a rapidly developing repository. All the pain of the above sequence is from the multi binary checks that have been added. granted the above can be addressed by refactoring `cmd/epm/commands.go` as it currently stands to exempt `plop` and `refs` from the no chain checked out error that is throwing, but still this feels like we're making this much more complicated than it needs to be with respect to development pipeline, dependency management and cross platform compilation ability.

again, if there is some major benefit to having these blockchains here in the repo I'm definitely interested.

Also I still haven't heard what benefit having non thelonious chains in this repository brings us, our users, or what value it adds to other projects vis a vis the cost to us of maintaining our forks of these projects, ensuring dependencies are kept up to date, and worrying about complicated compilation sequences. 

I mean to say what value add is epm bringing to tendermint if its just being used to wrap start and stop its blockchain functionality (which can be accomplished by exec its binary and piping and/or firing up a docker container with some env vars set and volumes mounted)? because the only thing that epm is functionally doing with non thelonious chains is starting and stopping them (besides the smart contract package stuff which really should be routed through a key signer daemon and onto an rpc so that it won't matter whether the blockchain client is running locally or remote) and *perhaps* configuring them.

**Comment by ebuchman** [comment]
> docker + better optimization of rpc (this issue really should be read in parallel with #161 )

ok. agreed. but it should still be painless to run the stuff locally without a docker env set up. though we could/should maintain peer nets so ppl can hook up right away to a chain without anything local. epm as is has been especially nice for integration testing of contracts/state updates.

> essential to whom? for what purpose? 

the grand question. multichain thinking/working isnt quite here yet. but its around the  corner. and we and other devs/admins will need tools to go plumbing between chains and to spin up contracts across them. there will be many tendermint chains.  there will be many thel chains, which while based on mint may diverge enough that its necessary to have both (like originally with thel and eth). we dont know yet whether or not there will be many eth chains. i dont disagree that we need to move more towards rpc/docker, to build something akin to a tutum for blockchains. but we will still have to maintain compatible rpc clients for them all, no? unless we leave that entirely up to thee js.

as for the plop id fiasco, apologies, its still rough on the edges, and yes, maybe handling it all is too demanding. on the other hand, its a rough implementation of a way to use modules as interfaces in go, which could prove useful, but is maybe too inhibiting in its current place and in our current stage of dev.

> Also I still haven't heard what benefit having non thelonious chains in this repository brings us, our users, or what value it adds to other projects vis a vis the cost to us of maintaining our forks of these projects, ensuring dependencies are kept up to date, and worrying about complicated compilation sequences. 

its been a bit of a pain, agreed. having eth around eg meant we could do solidity. but its tru epm has developed unfortunate bulkiness. part of that is because its also been used to quickly test chains after recompiling (wen working on vm, state, etc) without needing to upgrade remotes. granted if the individual chains' apis are sufficient then that stuff can/should just be tested within the chains repo. and if we keep the thelonious compiled in by default, i suppose its fine.

so lets bust this thing apart. will take up in #161

**Comment by compleatang** [comment]
> as for the plop id fiasco, apologies

that was merely a symptom for me to initiate this discussion. its an easy fix for that and refs.

**Comment by compleatang** [comment]
discussion to be continued in #161
