### ISSUE TITLE
P224 has been removed

### ISSUE THREAD

**Issue by KoenVingerhoets** [eris-ltd/epm-go#184]
Dear, I can't build epm-go due to an error on P224.
As far as I understand this patch on Ethereum, https://github.com/ethereum/go-ethereum/pull/1551/files, the P224 has been removed. And re-added a few hours ago :s

**Comment by androlo** [comment]
epm-go is being deprecated. 'eris-cli' is the replacement. Ethereum is being deprecated as well, and replaced with Tendermint. This has not yet been added to the general docs, but I would not recommend getting into the old stack. The current libraries are eris-db, eris-db.js, eris-contracts.js and eris-cli. The stack is (still) oriented towards javascript/node.js. If you intend on working from the command-line, there are other tools available as well, such as minty.

**Comment by KoenVingerhoets** [comment]
I'm checking out the approach in https://eng.erisindustries.com/tutorials/2015/04/25/make-thelonious-chain/
Refers to epm... hmmm

**Comment by androlo** [comment]
Yes, those still the official tools but only because we haven't updated the docs on the main site yet. You can still use, this issue will remain open, but it's only a matter of time before we completely switch over to the new tools and replace the docs. Getting started with the old tools now would be a waste of time imo.

**Comment by dennismckinnon** [comment]
Hello Thank you for pointing out this issue. I will have @ebuchman look into it and hopefully have it corrected soon.

@androlo is correct though that you have come to us at a very awkward time. Our old stack (based around epm and thelonious) is in the process of being replaced with the new stack (eris-cli and tendermint/erisdb) though the official documentation and tutorials have not been completed.

The readmes are currently the go to resource for the new stack which is now being used almost exclusively internally. So if you are the adventurous sort and don't mind digging in a bit I'll put the links below. Otherwise we will try to get this epm issue cleared up shortly.

Interacting with an existing tendermint chain from commandline mint-client is a (slightly awkward) method of doing it but has all the functionality of deploying contracts, making name reg entries and sending normal transactions. along with inspecting general information from the chain. this is actually a collection of small tools mintx mintinfo are the two primarily important ones.

https://github.com/eris-ltd/mint-client

Also if interacting with contracts on the blockchain you well need to convert arguments using the abi. I have written a tool which allow you to do that. (use its pack and unpack subcommands)

https://github.com/eris-ltd/eris-abi

If you are interested in rolling your own chain both tendermint and erisdb (a wrapper of tendermint allowing for some additional fancy features) support genesis.json manipulation. There is not yet (as far as I know complete documentation for this though.

https://github.com/tendermint/tendermint
https://github.com/eris-ltd/eris-db

If you want to write some javascript that interacts with the blockchain we have the eris-db.js and eris-contracts.js libraries which work with node applications. An example of such an application can be found in the smrt repo

https://github.com/eris-ltd/eris-db.js
https://github.com/eris-ltd/eris-contracts.js
https://github.com/eris-ltd/smrt

Again thanks for pointing this issue out and we will get on it as soon as possible

**Comment by KoenVingerhoets** [comment]
Thanks for the extensive reply @dennismckinnon . An awkward time indeed :) The eris-cli readme is for example quite compact ("WIP"). 

My purpose is to mimick a money transfer. Thus my aim is not to the have the latest version, I just want something working as an example. I'll see how far I can get woth the smrt and js libs.

**Comment by zramsay** [comment]
@KoenVingerhoets switch from master to develop & you'll see the readme.
