### ISSUE TITLE
Support Recursive Packages

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/epm-go#47]
```
include => github.com/eris-ltd/eris
include => github.com/blah-blah-blah/ponos
include => git.mycompany.org/1234/enyo

deploy => ...
```

One thing which we'll have to watch for is the in memory variables could be redundant across packages so instead of referencing included packages by their `{{variable}}` directly, we should reference them something like `{{package/variable}}` ... Don't really care the syntax too much but I think that gets in the vicinity of where we need to be going.

**Comment by compleatang** [comment]
also, am not married to the `include` keyword (although it does seem to make sense). we could also go with `package` as well.

**Comment by ebuchman** [comment]
right something like this is important so we can get access to multi contract suites. for sure. i will think about how best to do this.

**Comment by ebuchman** [comment]
ok so, the way I think this should work is basically you do those includes at the top, and those will be the root directories that epm will look for contracts you attempt to compile. like setting a PATH var. reasonable?

not suyre what you were saying about the vars tho casey

**Comment by compleatang** [comment]
Ya. Seems reasonable.

As to the vars, I mean within the included packages they will have `{{doug}}` for example. that `{{doug}}` would probably need to be referenced throughout the rest of the package deploy perhaps as `{{ponos.doug}}` or `{{ponos/doug}}` or somehow connoting that we're talking about the contract address for ponos' doug not enyo's doug or whatever.

**Comment by ebuchman** [comment]
so there's two things going on here. one is PATH variable to look for contracts in (ala https://github.com/eris-ltd/epm-go/issues/24). The other is access to other vars. the later seems more complicated since vars are defined in a given pdx and just because I include a path (so I can use its contracts) doesn't mean I'm inhereting some vars - where would they even be coming from?

now, it is possible to deploy a pdx from a pdx. so maybe we can add something to the syntax so that any variables coming from that nested deploy (eg a DOUG) get prefixed by the name given to that deploy (say PONOS_DOUG).  I'm not sure how frequently used something like that will be but shouldn't be too hard.

**Comment by compleatang** [comment]
yeah. that is more in line with my thinking --> namely that the nested bit would be a pdx rather than a contract path. and then in the "master" pdx it would drop a varname for the included pdx, then epm would deploy the nested pdx, use its vars and expose those to the master pdx with that `varname` `separator` (of some kind, `.` `_` `-` w/e) `nestedvarname` ...

**Comment by ebuchman** [comment]
eg: 
```
include:
        github.com/eris-ltd/eris-std-lib => {{esl}}
        github.com/eris-ltd/eris-std-lib/epm => {{eslepm}}

deploy:
        a.lll => {{addr}}
deploy:
        {{esl}}/epm/aa.lll => {{addr2}}
deploy:
        {{eslepm}}/aa.lll => {{addr3}}
```

**Comment by ebuchman** [comment]
eg.
```
epm:   
        definitions/test_deploy.epm => dep
transact:
        {{dep.addr}} => 0x3 0x4
```

where {{addr}} is the result of a deploy in `test_deploy.epm`
